name: David Carter
favicon: null
layout_spectrum: 0.5755718708969653
typography_spectrum: 0.584155905758962
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.42289995145983994
  lightness: 0.9997394818346947
  saturation: 0.16425454150885344
  rhythmicContrast: 0.6233179341070354
purpose: []
